# model
obs_len: 16    # number of observation frames
pred_len: 24   # number of prediction frames
num_class: 3   # number of classes for prediction
nei_radius: [5, 2, 3, 2]   # observe radius, neighborhood radius

embed_size: 128
num_decode_layers: 2
num_modes: 30

# training
lr: 0.0001
batch_size: 128
epoch: 100         # total number of epochs for training
EPOCH_BATCHES: 100 # number of batches per epoch, None for data_length//batch_size
TEST_SINCE: 500    # the epoch after which performing testing during training

# testing
PRED_SAMPLES: 10   # best of N samples

# evaluation
WORLD_SCALE: 1